
default_platform(:android)

platform :android do
  desc "Lane for android firebase app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:40760888613:android:5dc1d276cc2fbba0cb1ecc",
    firebase_cli_token: "1//03TLs1NPcpktyCgYIARAAGAMSNgF-L9Ir9_ljNqgJ1wWWP3b7anPI2KDRdtdHdq79DNN3a4CBzsc51mbeemhC5aU1J3mlb1u-RQ",
    android_artifact_type: "APK" ,
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "ahmedbayomy238@gmail.com",
    release_notes: "This is a test fastlane firebase distribution"
  )
  end
end
